---
- name: Update all packages to their latest version Debian
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Instalando pacotes essenciais
  apt:
    name:
      - vim
      - net-tools
      - telnet
      - nmap
      - curl
      - unzip
      - wget
      - htop
      - nginx
    state: present

- name: Set a hostname
  ansible.builtin.hostname:
    name: DevOps

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/html/

- name: Start service nginx, if not started
  ansible.builtin.service:
    name: nginx
    state: started

- name: user example present
  ansible.builtin.user:
    name: "{{ user_linux }}"
    password: "{{ 'password' | password_hash('sha512', 'teste') }}"
    groups:
      - adm
    state: "present"
    shell: "/bin/bash"
    system: false
    create_home: true
    home: "/home/{{ user_linux }}"
    comment: "Ansible create user"
    generate_ssh_key: true